// FrontendV2/src/app/features/login/pages/login/login.component.ts
import { Component, OnInit, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import Swal from 'sweetalert2';
import { NavbarComponent } from '../../../../shared/components/nav-bar/nav-bar';
import { UserService } from '../../../../core/services/user.service';
import { AuthService } from '../../../../core/services/auth.service';
import { isAdminRole } from '../../../../shared/utils/roles';
import { getAndClearRedirectUrl } from '../../../../shared/utils/auth';
import { environment } from '../../../../../environments/environment';

const GOOGLE_CLIENT_ID = environment.googleClientId;

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, NavbarComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  isRegister = false;
  nombre = '';
  apellido = '';
  email = '';
  password = '';
  showPassword = false;
  authMessage = '';
  passwordError = '';

  readonly googleClientId = GOOGLE_CLIENT_ID;

  constructor(
    private userService: UserService,
    private authService: AuthService,
    private router: Router,
    private route: ActivatedRoute,
    private ngZone: NgZone,
  ) {}

  ngOnInit(): void {
    // Mostrar mensaje desde query param (equivalente a $page.url.searchParams)
    const message = this.route.snapshot.queryParamMap.get('message');
    if (message) {
      this.authMessage = message;
      Swal.fire({
        title: 'Acceso requerido',
        text: message,
        icon: 'info',
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000,
      });
    }

    // Inicializar Google Sign-In
    if (this.googleClientId) {
      this.loadGoogleScript().then(() => this.initGoogle());
    }
  }

  //Password rules
  get pwdRules() {
    return {
      length: this.password.length >= 8,
      upper: /[A-Z]/.test(this.password),
      lower: /[a-z]/.test(this.password),
      number: /\d/.test(this.password),
      special: /[!@#$%^&*(),.?":{}|<>]/.test(this.password),
    };  
  }

  get isPasswordValid(): boolean {
    return Object.values(this.pwdRules).every(Boolean);
  }

  // ── Google Sign-In ────────────────────────────────
  private loadGoogleScript(): Promise<void> {
    return new Promise((resolve, reject) => {
      if ((window as any).google?.accounts?.id) return resolve();
      const script = document.createElement('script');
      script.src = 'https://accounts.google.com/gsi/client';
      script.async = true;
      script.defer = true;
      script.onload = () => resolve();
      script.onerror = () => reject(new Error('Failed to load Google Identity Services'));
      document.head.appendChild(script);
    });
  }

  private initGoogle(): void {
    const g = (window as any).google;
    if (!g) return;

    if (!(window as any).__pethouse_google_initialized) {
      g.accounts.id.initialize({
        client_id: this.googleClientId,
        callback: (response: any) => this.ngZone.run(() => this.handleCredentialResponse(response)),
      });
      (window as any).__pethouse_google_initialized = true;
    }

    try {
      g.accounts.id.renderButton(document.getElementById('googleSignInDiv'), {
        theme: 'outline',
        size: 'large',
        width: '280',
      });
    } catch {
      /* ignore */
    }
  }

  async handleCredentialResponse(response: any): Promise<void> {
    if (!response?.credential) return;
    try {
      const data = await this.userService.googleLogin(response.credential);
      this.authService.setAuth(data.user, data.access_token);
      Swal.fire({ title: 'Bienvenido', text: `Hola ${data.user.name}`, icon: 'success' });
      this.redirectAfterLogin(data.user);
    } catch {
      Swal.fire('Error', 'No se pudo iniciar sesión con Google.', 'error');
    }
  }

  handleGoogleClick(): void {
    this.loadGoogleScript().then(() => {
      this.initGoogle();
      const sdkBtn = document.querySelector('#googleSignInDiv button') as HTMLElement;
      if (sdkBtn) {
        sdkBtn.click();
        return;
      }
      (window as any).google?.accounts?.id?.prompt();
    });
  }

  // ── Login / Register ──────────────────────────────
  async handleSubmit(): Promise<void> {
    this.passwordError = '';

    if (this.isRegister) {
      await this.register();
    } else {
      await this.login();
    }
  }

  private async register(): Promise<void> {
    const userData = {
      role_id: 2,
      name: this.nombre,
      last_name: this.apellido,
      email: this.email,
      password: this.password,
    };

    try {
      await this.userService.registerUser(userData);
      Swal.fire({
        title: 'Éxito',
        text: 'Usuario registrado correctamente. Ahora puedes iniciar sesión.',
        icon: 'success',
      });
      this.nombre = '';
      this.apellido = '';
      this.email = '';
      this.password = '';
      this.isRegister = false;
    } catch (error: any) {
      this.passwordError = error?.error?.detail || error.message || 'Error registrando usuario';
      const msg = this.passwordError;
      if (!msg.includes('contraseña') && !msg.includes('caracter')) {
        Swal.fire({ title: 'Error', text: msg, icon: 'error' });
      }
    }
  }

  private async login(): Promise<void> {
    try {
      const result = await this.userService.loginUser(this.email, this.password);
      this.authService.setAuth(result.user, result.access_token);
      Swal.fire({ title: 'Bienvenido', text: `Hola ${result.user.name}`, icon: 'success' });
      this.redirectAfterLogin(result.user);
    } catch (error: any) {
      Swal.fire({
        title: 'Error',
        text: error?.error?.detail || error.message || 'Credenciales incorrectas',
        icon: 'error',
      });
    }
  }

  private redirectAfterLogin(user: any): void {
    const redirectUrl = getAndClearRedirectUrl();
    if (redirectUrl) {
      this.router.navigateByUrl(redirectUrl);
    } else {
      this.router.navigate([isAdminRole(user) ? '/admin' : '/']);
    }
  }

  toggleMode(): void {
    this.isRegister = !this.isRegister;
    this.passwordError = '';
  }

  //Pruebar con credenciales predefinidas para facilitar el testing
  readonly testCredentials = {
    admin: { email: 'admin@pethouse.com', password: 'Admin123!' },
    usuario: { email: 'usuario@pethouse.com', password: 'Usuario123!' },
  };

  fillTestCredentials(role: 'admin' | 'usuario'): void {
    this.email = this.testCredentials[role].email;
    this.password = this.testCredentials[role].password;
  }
}

<app-navbar [variant]="'login'" [showLogin]="false" />

<section class="login-wrapper">
  <div class="login-deco deco-1"></div>
  <div class="login-deco deco-2"></div>

  <div class="login-card px-4">
    <div class="card-badge">🐾 PET HOUSE</div>

    <h2>{{ isRegister ? 'Crear cuenta' : 'Bienvenido' }}</h2>
    <p class="subtitle">
      {{
        isRegister
          ? 'Regístrate para comenzar una nueva historia'
          : 'Inicia sesión para continuar con tu búsqueda'
      }}
    </p>

    <!-- Formulario -->
    <div>
      <!-- Nombre y apellido (solo registro) -->
      <div *ngIf="isRegister" class="row g-2 mb-3">
        <div class="col-md-6 text-start">
          <label for="nombre" class="small fw-bold">Nombre</label>
          <input
            id="nombre"
            class="form-control form-control-sm"
            type="text"
            [(ngModel)]="nombre"
            required
          />
        </div>
        <div class="col-md-6 text-start">
          <label for="apellido" class="small fw-bold">Apellido</label>
          <input
            id="apellido"
            class="form-control form-control-sm"
            type="text"
            [(ngModel)]="apellido"
            required
          />
        </div>
      </div>

      <!-- Email -->
      <div class="input-group mb-3">
        <label class="small fw-bold">Correo electrónico</label>
        <input
          class="form-control form-control-sm"
          type="email"
          [(ngModel)]="email"
          placeholder="ejemplo@email.com"
          required
        />
      </div>

      <!-- Contraseña -->
      <div class="input-group mb-3">
        <label class="small fw-bold">Contraseña</label>
        <div class="password-wrapper">
          <input
            class="form-control form-control-sm"
            [type]="showPassword ? 'text' : 'password'"
            [(ngModel)]="password"
            placeholder="••••••••"
            required
          />
          <span class="toggle-password" (click)="showPassword = !showPassword">
            {{ showPassword ? '👁' : '👁‍🗨' }}
          </span>
        </div>

        <!-- Reglas contraseña (solo registro) -->
        <div *ngIf="isRegister" class="password-guidelines mt-3 p-3 rounded-3">
          <div class="row g-1">
            <div
              class="col-6 x-small"
              [class.text-success]="pwdRules.length"
              [class.text-muted]="!pwdRules.length"
            >
              <i
                class="bi"
                [class.bi-check-circle-fill]="pwdRules.length"
                [class.bi-circle]="!pwdRules.length"
              ></i>
              8+ caracteres
            </div>
            <div
              class="col-6 x-small"
              [class.text-success]="pwdRules.upper && pwdRules.lower"
              [class.text-muted]="!(pwdRules.upper && pwdRules.lower)"
            >
              <i
                class="bi"
                [class.bi-check-circle-fill]="pwdRules.upper && pwdRules.lower"
                [class.bi-circle]="!(pwdRules.upper && pwdRules.lower)"
              ></i>
              Mayúsculas y minúsculas
            </div>
            <div
              class="col-6 x-small"
              [class.text-success]="pwdRules.number"
              [class.text-muted]="!pwdRules.number"
            >
              <i
                class="bi"
                [class.bi-check-circle-fill]="pwdRules.number"
                [class.bi-circle]="!pwdRules.number"
              ></i>
              Número
            </div>
            <div
              class="col-6 x-small"
              [class.text-success]="pwdRules.special"
              [class.text-muted]="!pwdRules.special"
            >
              <i
                class="bi"
                [class.bi-check-circle-fill]="pwdRules.special"
                [class.bi-circle]="!pwdRules.special"
              ></i>
              Símbolo
            </div>
          </div>
        </div>

        <div *ngIf="passwordError" class="error-text text-danger x-small mt-2 fw-bold">
          {{ passwordError }}
        </div>
      </div>

      <!-- Submit -->
      <button
        class="btn-login py-2 mt-3"
        (click)="handleSubmit()"
        [disabled]="isRegister && !isPasswordValid"
      >
        {{ isRegister ? 'Registrarse' : 'Iniciar Sesión' }}
      </button>
    </div>

    <!-- Google Sign-In -->
    <div class="mt-3 d-flex justify-content-center google-signin-wrapper">
      <ng-container *ngIf="googleClientId; else noGoogle">
        <div id="googleSignInDiv" (click)="handleGoogleClick()"></div>
      </ng-container>
      <ng-template #noGoogle>
        <div class="google-missing text-center p-3">
          <p class="mb-1">Google Sign-In no está configurado.</p>
          <small class="text-muted">
            Agrega <strong>GOOGLE_CLIENT_ID</strong> en el componente y reinicia.
          </small>
        </div>
      </ng-template>
    </div>

    <!-- Toggle login/registro -->
    <p class="footer-text">
      <ng-container *ngIf="!isRegister">
        ¿No tienes cuenta?
        <a href="#" (click)="$event.preventDefault(); toggleMode()">Regístrate</a>
      </ng-container>
      <ng-container *ngIf="isRegister">
        ¿Ya tienes cuenta?
        <a href="#" (click)="$event.preventDefault(); toggleMode()">Inicia sesión</a>
      </ng-container>
    </p>
  </div>
</section>

// Frontend/src/routes/login/+page.svelte
<script>
	import { createUser, loginUser, registerUser } from '../../api/user_service.js';
	import { fade, fly } from 'svelte/transition';
	import Navbar from '$lib/components/Navbar.svelte';
	import { setAuth } from '$lib/stores/auth.js';
	import { getAndClearRedirectUrl } from '$lib/utils/auth.js';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import Swal from 'sweetalert2';
	// svelte-ignore export_let_unused
		export let data;

	let isRegister = false;

	let nombre = '';
	let apellido = '';
	let email = '';
	let password = '';
	let showPassword = false;
	let authMessage = '';
	let passwordError = '';

	// Reglas de validación reactivas
	$: pwdRules = {
		length: password.length >= 8,
		upper: /[A-Z]/.test(password),
		lower: /[a-z]/.test(password),
		number: /\d/.test(password),
		special: /[!@#$%^&*(),.?":{}|<>]/.test(password)
	};

	$: isPasswordValid = Object.values(pwdRules).every(Boolean);

	// Get message from URL if present
	$: if ($page.url.searchParams.has('message')) {
		authMessage = $page.url.searchParams.get('message');
		// Show the message in a toast or alert
		if (authMessage) {
			Swal.fire({
				title: 'Acceso requerido',
				text: authMessage,
				icon: 'info',
				toast: true,
				position: 'top-end',
				showConfirmButton: false,
				timer: 3000
			});
		}
	}

	async function handleSubmit() {
		if (isRegister) {
			// =========================
			// REGISTRO
			// =========================
			const userData = {
				role_id: 2,  // Usuario normal por defecto
				name: nombre,
				last_name: apellido,
				email: email,
				password: password
			};

			try {
				const result = await registerUser(userData);

				Swal.fire({
					title: 'Éxito',
					text: 'Usuario registrado correctamente. Ahora puedes iniciar sesión.',
					icon: 'success'
				});

				// limpiar campos
				nombre = '';
				apellido = '';
				email = '';
				password = '';

				isRegister = false;

			} catch (error) {
				passwordError = error.message;
				// Si el error es de la contraseña, no mostramos modal, solo el texto abajo
				if (!error.message.includes('contraseña') && !error.message.includes('caracter')) {
					Swal.fire({
						title: 'Error',
						text: error.message || 'Error registrando usuario',
						icon: 'error'
					});
				}
			}

		} else {
		
			try {
				const result = await loginUser(email, password);
				
				console.log('Login result:', result);

				// guardar token y usuario
			setAuth(result.access_token, result.user);
           
				Swal.fire({
					title: 'Bienvenido',
					text: `Hola ${result.user.name}`,
					icon: 'success'
				});

				// Verificar si hay una URL de redirección guardada
				const redirectUrl = getAndClearRedirectUrl();

				if (redirectUrl) {
					// Redirigir a la URL guardada
					goto(redirectUrl);
				} else {
					// Redirección por rol si no hay URL guardada
					const roleId = result.user.role_id;
					if (roleId === 1) {
						goto('/admin');
					} else {
						// Usuario normal va a la página principal
						goto('/');
					}
				}

			} catch (error) {
				Swal.fire({
					title: 'Error',
					text: error.message || 'Credenciales incorrectas',
					icon: 'error'
				});
			}
		}
	}
</script>

<Navbar />
<section class="login-wrapper" in:fade>
	<div class="login-card px-4" in:fly={{ y: 30, duration: 400, opacity: 0 }}>
		<h2>{isRegister ? 'Crear cuenta' : 'Bienvenido'}</h2>
		<p class="subtitle">
			{isRegister ? 'Regístrate para comenzar' : 'Inicia sesión para continuar'}
		</p>

		<form on:submit|preventDefault={handleSubmit}>
			{#if isRegister}
				<div class="row g-2 mb-2" in:fly={{ y: -15, duration: 500 }}>
					<div class="col-md-6 text-start">
						<label for="nombre" class="small fw-bold">Nombre</label>
						<input id="nombre" class="form-control form-control-sm" type="text" bind:value={nombre} required />
					</div>
					<div class="col-md-6 text-start">
						<label for="apellido" class="small fw-bold">Apellido</label>
						<input id="apellido" class="form-control form-control-sm" type="text" bind:value={apellido} required />
					</div>
				</div>
			{/if}

			<div class="input-group mb-2">
				<label class="small fw-bold">Correo electrónico</label>
				<input class="form-control form-control-sm" type="email" bind:value={email} placeholder="ejemplo@email.com" required />
			</div>

			<div class="input-group mb-2">
				<label class="small fw-bold">Contraseña</label>
				<div class="password-wrapper">
					<input
						class="form-control form-control-sm"
						type={showPassword ? 'text' : 'password'}
						bind:value={password}
						placeholder="••••••••"
						required
					/>
					<!-- svelte-ignore a11y_click_events_have_key_events -->
					<!-- svelte-ignore a11y_no_static_element_interactions -->
					<span class="toggle-password" on:click={() => (showPassword = !showPassword)}>
						{showPassword ? '👁' : '👁‍🗨'}
					</span>
				</div>

				{#if isRegister}
					<div class="password-guidelines mt-2 p-2 rounded-3 bg-light border-0">
						<div class="row g-1">
							<div class="col-6 {pwdRules.length ? 'text-success' : 'text-muted'} x-small">
								<i class="bi {pwdRules.length ? 'bi-check-circle-fill' : 'bi-circle'}"></i> 8+ chars
							</div>
							<div class="col-6 {pwdRules.upper && pwdRules.lower ? 'text-success' : 'text-muted'} x-small">
								<i class="bi {pwdRules.upper && pwdRules.lower ? 'bi-check-circle-fill' : 'bi-circle'}"></i> Aa
							</div>
							<div class="col-6 {pwdRules.number ? 'text-success' : 'text-muted'} x-small">
								<i class="bi {pwdRules.number ? 'bi-check-circle-fill' : 'bi-circle'}"></i> Número
							</div>
							<div class="col-6 {pwdRules.special ? 'text-success' : 'text-muted'} x-small">
								<i class="bi {pwdRules.special ? 'bi-check-circle-fill' : 'bi-circle'}"></i> Especial
							</div>
						</div>
					</div>
					
					{#if passwordError}
						<div class="error-text text-danger x-small mt-1 fw-bold">
							{passwordError}
						</div>
					{/if}
				{/if}
			</div>

			<button class="btn-login py-2 mt-3" disabled={isRegister && !isPasswordValid}>
				{isRegister ? 'Registrarse' : 'Iniciar Sesión'}
			</button>
			
		</form>

		<p class="footer-text">
			{#if !isRegister}
				¿No tienes cuenta?

				<a href="..." on:click|preventDefault={() => (isRegister = true)}> Regístrate </a>
			{:else}
				¿Ya tienes cuenta?
				<a href="..." on:click|preventDefault={() => (isRegister = false)}> Inicia sesión </a>
			{/if}
		</p>
	</div>
</section>

<style>
	.login-wrapper {
		min-height: 100vh;
		display: flex;
		justify-content: center;
		align-items: center;
		background: linear-gradient(135deg, #ecd75f, #b89a14);
	}

	.login-card {
		background: white;
		padding: 2rem 1.5rem;
		border-radius: 24px;
		width: 100%;
		max-width: 420px;
		box-shadow: 0 20px 40px rgba(0, 0, 0, 0.2);
		text-align: center;
		margin: 1rem;
	}

	.login-card h2 {
		font-weight: 700;
		margin-bottom: 0.5rem;
	}

	.subtitle {
		color: #6c757d;
		margin-bottom: 1.5rem;
	}

	.input-group {
		display: flex;
		flex-direction: column;
		margin-bottom: 1.2rem;
		text-align: left;
	}

	.input-group label {
		font-size: 1rem;
		font-weight: 600;
		display: block;
		margin-bottom: 0.2rem;
	}

	.input-group input {
		width: 100%;
		padding: 0.3rem;
		border-radius: 12px;
		border: 1px solid #dfe1e2;
		transition: all 0.2s ease;
	}

	.input-group input:focus {
		border-color: #0d6efd;
		box-shadow: 0 0 0 3px rgba(13, 110, 253, 0.2);
		outline: none;
	}

	.password-wrapper {
		position: relative;
	}

	.password-wrapper input {
		padding-right: 87px; /* espacio para el icono */
	}

	.toggle-password {
		position: absolute;
		right: 6px;
		top: 50%;
		transform: translateY(-50%);
		cursor: pointer;
		font-size: 1rem;
		user-select: none;
		color: #6c757d;
		transition: 0.2s ease;
	}

	.toggle-password:hover {
		color: #b7b921;
	}

	.btn-login {
		width: 100%;
		padding: 0.8rem;
		border-radius: 12px;
		border: none;
		background: linear-gradient(135deg, #ced121, #828a1b);
		color: rgb(253, 253, 247);
		font-weight: 600;
		cursor: pointer;
		transition: all 0.25s ease;
		box-shadow: 0 8px 20px rgba(13, 110, 253, 0.3);
		margin-top: 0.5rem;
	}

	.btn-login:hover {
		transform: translateY(-3px);
		box-shadow: 0 12px 30px rgba(13, 110, 253, 0.4);
	}

	.footer-text {
		margin-top: 1.5rem;
		font-size: 0.9rem;
		color: #6c757d;
	}

	.footer-text a {
		color: #0d6efd;
		text-decoration: none;
		font-weight: 600;
	}

	.footer-text a:hover {
		text-decoration: underline;
	}

	@media (max-width: 480px) {
		.login-card {
			padding: 2rem;
		}
	}
	#admin-login {
		background: linear-gradient(135deg, #b89a14, #ecd75f);
		color: #333;
		box-shadow: 0 8px 20px rgba(184, 154, 20, 0.3);
	}

	.password-guidelines {
		text-align: left;
		background-color: #f8f9fa !important;
	}

	.x-small {
		font-size: 0.75rem;
	}

	.password-guidelines .row > div {
		display: flex;
		align-items: center;
		gap: 5px;
		transition: all 0.3s ease;
	}

	.error-text {
		text-align: left;
	}

	.btn-login:disabled {
		background: #e9ecef;
		color: #adb5bd;
		cursor: not-allowed;
		box-shadow: none;
		transform: none;
	}
</style>
