// FrontendV2/src/app/features/admin/pages/historial/historial.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import Swal from 'sweetalert2';
import { AdminNavbarComponent } from '../../../../shared/components/admin-navbar/admin-navbar';
import { AuditService } from '../../../../core/services/audit.service';

interface ActionBadge {
  class: string;
  label: string;
  icon: string;
}

@Component({
  selector: 'app-admin-historial',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, AdminNavbarComponent],
  templateUrl: './historial.component.html',
  styleUrls: ['./historial.component.css'],
})
export class AdminHistorialComponent implements OnInit {
  users: any[] = [];
  auditLogs: any[] = [];
  filteredLogs: any[] = [];
  loading = false;
  showDetailModal = false;
  selectedLog: any = null;

  // Filtros
  filterAction = '';
  filterResource = '';
  filterUser = '';
  startDate = '';
  endDate = '';
  searchTerm = '';

  // Paginación
  currentPage = 1;
  pageSize = 20;
  pageSizeOptions = [20, 50, 100];
  hasNextPage = false;

  constructor(private auditService: AuditService) {}

  async ngOnInit(): Promise<void> {
    await this.loadUsers();
    await this.fetchAuditLogs();
  }

  async loadUsers(): Promise<void> {
    try {
      this.users = await this.auditService.getUsers();
    } catch {
      this.users = [];
    }
  }

  async fetchAuditLogs(): Promise<void> {
    this.loading = true;
    try {
      const params: any = {
        limit: this.pageSize,
        offset: (this.currentPage - 1) * this.pageSize,
      };

      if (this.filterAction) params.action = this.filterAction;
      if (this.filterResource) params.resource = this.filterResource;
      if (this.filterUser) params.user_id = this.filterUser;
      if (this.startDate) params.start_date = new Date(this.startDate).toISOString();
      if (this.endDate) {
        const end = new Date(this.endDate);
        end.setHours(23, 59, 59, 999);
        params.end_date = end.toISOString();
      }

      const logs = await this.auditService.getAuditLogs(params);
      this.auditLogs = this.decorateLogsWithUserName(logs);
      this.hasNextPage = this.auditLogs.length === this.pageSize;

      this.applySearch();
    } catch (error) {
      Swal.fire({
        icon: 'error',
        title: 'Error de Carga',
        text: 'No se pudo obtener el historial. Verifica tu conexión.',
        confirmButtonColor: '#ff6b6b',
      });
    } finally {
      this.loading = false;
    }
  }

  decorateLogsWithUserName(logs: any[]): any[] {
    const userMap: Record<number, string> = {};
    this.users.forEach((u: any) => {
      userMap[u.id] = `${u.name} ${u.last_name || ''}`.trim();
    });

    return logs.map((l) => ({
      ...l,
      user_name: l.user_id ? userMap[l.user_id] || `Usuario #${l.user_id}` : 'Sistema',
    }));
  }

  applySearch(): void {
    const term = this.searchTerm.trim().toLowerCase();
    if (!term) {
      this.filteredLogs = this.auditLogs;
      return;
    }
    this.filteredLogs = this.auditLogs.filter((log) => {
      const details = typeof log.details === 'string' ? log.details : '';
      const userName = (log.user_name || '').toLowerCase();
      const resourceId = `${log.resource_id ?? ''}`;
      const status = (log.status || '').toLowerCase();
      const action = (log.action || '').toLowerCase();
      const resource = (log.resource || '').toLowerCase();

      return (
        action.includes(term) ||
        resource.includes(term) ||
        details.toLowerCase().includes(term) ||
        userName.includes(term) ||
        resourceId.includes(term) ||
        status.includes(term)
      );
    });
  }

  async onFiltersSubmit(): Promise<void> {
    this.currentPage = 1;
    await this.fetchAuditLogs();
  }

  async changePageSize(): Promise<void> {
    this.currentPage = 1;
    await this.fetchAuditLogs();
  }

  async goToPreviousPage(): Promise<void> {
    if (this.currentPage <= 1 || this.loading) return;
    this.currentPage -= 1;
    await this.fetchAuditLogs();
  }

  async goToNextPage(): Promise<void> {
    if (!this.hasNextPage || this.loading) return;
    this.currentPage += 1;
    await this.fetchAuditLogs();
  }

  async exportToCSV(): Promise<void> {
    try {
      const params: any = {};
      if (this.filterAction) params.action = this.filterAction;
      if (this.filterResource) params.resource = this.filterResource;
      if (this.filterUser) params.user_id = this.filterUser;
      if (this.startDate) params.start_date = new Date(this.startDate).toISOString();
      if (this.endDate) params.end_date = new Date(this.endDate).toISOString();

      const data = await this.auditService.exportAuditLogsCSV(params);
      const blob = new Blob([data.content], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = data.filename;
      a.click();
      URL.revokeObjectURL(url);

      Swal.fire({
        icon: 'success',
        title: '¡Exportado!',
        text: 'El archivo CSV se ha descargado.',
        confirmButtonColor: '#4361ee',
      });
    } catch {
      Swal.fire('Error', 'No se pudo exportar el historial.', 'error');
    }
  }

  async resetFilters(): Promise<void> {
    this.filterAction = '';
    this.filterResource = '';
    this.filterUser = '';
    this.startDate = '';
    this.endDate = '';
    this.searchTerm = '';
    this.currentPage = 1;
    await this.fetchAuditLogs();
  }

  viewDetails(log: any): void {
    this.selectedLog = log;
    this.showDetailModal = true;
  }

  closeModal(): void {
    this.showDetailModal = false;
    this.selectedLog = null;
  }

  formatDate(dateString: string): string {
    if (!dateString) return '-';
    return new Date(dateString).toLocaleString('es-CO', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  getActionBadge(action: string): ActionBadge {
    const config: Record<string, ActionBadge> = {
      create: { class: 'badge-create', label: 'Crear', icon: 'bi-plus-circle' },
      update: { class: 'badge-update', label: 'Editar', icon: 'bi-pencil' },
      delete: { class: 'badge-delete', label: 'Borrar', icon: 'bi-trash' },
      login: { class: 'badge-login', label: 'Login', icon: 'bi-box-arrow-in-right' },
      login_failed: { class: 'badge-failed', label: 'Fallo', icon: 'bi-exclamation-triangle' },
    };
    return config[action] ?? { class: 'bg-secondary', label: action, icon: 'bi-dot' };
  }

  getDetailsJson(log: any): string {
    const payload = log.changes || log.details;
    if (!payload) return 'Sin detalles adicionales.';
    if (typeof payload === 'string') return payload;
    return JSON.stringify(payload, null, 2);
  }
}

<app-admin-navbar />

<main class="history-page py-5">
  <div class="container">
    <!-- Header -->
    <header
      class="d-flex flex-column flex-md-row justify-content-between align-items-end mb-4 gap-3"
    >
      <div>
        <span class="history-badge mb-2">📋 Auditoría General</span>
        <h1 class="fw-bold display-6 mb-0">Historial de Actividad</h1>
        <p class="text-muted">Monitorea cada cambio y acción realizada en el sistema.</p>
      </div>
      <div class="d-flex gap-2">
        <button class="btn btn-export shadow-sm" (click)="exportToCSV()">
          <i class="bi bi-download me-2"></i> Exportar CSV
        </button>
      </div>
    </header>

    <!-- Filtros -->
    <div class="card filter-card mb-4 p-4 shadow-sm">
      <div class="row g-3">
        <div class="col-12 col-md-3">
          <label class="cartoon-label">Acción</label>
          <select class="form-select cartoon-input" [(ngModel)]="filterAction">
            <option value="">Todas las acciones</option>
            <option value="create">Crear</option>
            <option value="update">Actualizar</option>
            <option value="delete">Eliminar</option>
            <option value="login">Inicio Sesión</option>
            <option value="login_failed">Login fallido</option>
          </select>
        </div>
        <div class="col-12 col-md-3">
          <label class="cartoon-label">Recurso</label>
          <select class="form-select cartoon-input" [(ngModel)]="filterResource">
            <option value="">Todos los recursos</option>
            <option value="user">Usuarios</option>
            <option value="pet">Mascotas</option>
            <option value="adoption">Adopciones</option>
          </select>
        </div>
        <div class="col-12 col-md-3">
          <label class="cartoon-label">Usuario</label>
          <select class="form-select cartoon-input" [(ngModel)]="filterUser">
            <option value="">Todos los usuarios</option>
            <option *ngFor="let user of users" [value]="user.id">
              {{ user.name }} {{ user.last_name || '' }}
            </option>
          </select>
        </div>
        <div class="col-12 col-md-3">
          <label class="cartoon-label">Rango de Fechas</label>
          <div class="input-group">
            <input type="date" class="form-control cartoon-input" [(ngModel)]="startDate" />
            <span class="input-group-text bg-transparent border-0">al</span>
            <input type="date" class="form-control cartoon-input" [(ngModel)]="endDate" />
          </div>
        </div>
        <div class="col-12 d-flex flex-wrap align-items-end justify-content-between gap-2 mt-2">
          <div class="d-flex align-items-center gap-2">
            <label class="cartoon-label mb-0">Registros por página</label>
            <select
              class="form-select cartoon-input page-size-select"
              [(ngModel)]="pageSize"
              (change)="changePageSize()"
            >
              <option *ngFor="let size of pageSizeOptions" [value]="size">{{ size }}</option>
            </select>
          </div>
          <div class="d-flex align-items-center gap-2">
            <button class="btn btn-search" (click)="onFiltersSubmit()">
              <i class="bi bi-search me-1"></i> Filtrar
            </button>
            <button class="btn btn-outline-secondary rounded-pill" (click)="resetFilters()">
              <i class="bi bi-arrow-counterclockwise me-1"></i> Limpiar
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Búsqueda rápida -->
    <div class="search-box mb-4">
      <input
        type="text"
        class="form-control form-control-lg cartoon-input ps-4"
        placeholder="🔍 Buscar por acción, recurso, estado, usuario o detalles..."
        [(ngModel)]="searchTerm"
        (input)="applySearch()"
      />
    </div>

    <!-- Tabla -->
    <div class="card border-0 shadow-sm rounded-4 overflow-hidden">
      <div class="table-responsive">
        <table class="table table-hover align-middle mb-0">
          <thead class="table-ink text-white">
            <tr>
              <th class="ps-4">Usuario</th>
              <th>Acción</th>
              <th>Recurso</th>
              <th>Fecha y Hora</th>
              <th>Estado</th>
              <th class="text-center pe-4">Detalle</th>
            </tr>
          </thead>
          <tbody>
            <!-- Loading -->
            <tr *ngIf="loading">
              <td colspan="6" class="text-center py-5">
                <div class="spinner-border text-warning" role="status"></div>
                <p class="mt-2 fw-bold">Cargando bitácora...</p>
              </td>
            </tr>

            <!-- Empty -->
            <tr *ngIf="!loading && filteredLogs.length === 0">
              <td colspan="6" class="text-center py-5 text-muted">
                <i class="bi bi-journal-x display-4 d-block mb-3 opacity-20"></i>
                No se encontraron registros con esos filtros.
              </td>
            </tr>

            <!-- Rows -->
            <tr *ngFor="let log of filteredLogs" class="log-row">
              <td class="ps-4">
                <div class="d-flex align-items-center gap-2">
                  <div class="user-avatar-small">{{ log.user_id ? 'U' : 'S' }}</div>
                  <div>
                    <div class="fw-bold small">
                      {{ log.user_name || (log.user_id ? 'Usuario #' + log.user_id : 'Sistema') }}
                    </div>
                    <div class="text-muted x-small">{{ log.ip_address || 'Sin IP' }}</div>
                  </div>
                </div>
              </td>
              <td>
                <span class="badge-cartoon" [ngClass]="getActionBadge(log.action).class">
                  <i class="bi me-1" [ngClass]="getActionBadge(log.action).icon"></i>
                  {{ getActionBadge(log.action).label }}
                </span>
              </td>
              <td>
                <span class="fw-bold text-dark">{{ log.resource }}</span>
                <span class="text-muted small">#{{ log.resource_id || '-' }}</span>
              </td>
              <td class="text-muted small">{{ formatDate(log.timestamp) }}</td>
              <td>
                <span *ngIf="log.status === 'success'" class="text-success small fw-bold">
                  <i class="bi bi-check-circle-fill"></i> Ok
                </span>
                <span *ngIf="log.status !== 'success'" class="text-danger small fw-bold">
                  <i class="bi bi-x-circle-fill"></i> Error
                </span>
              </td>
              <td class="text-center pe-4">
                <button class="btn btn-detail-circle" (click)="viewDetails(log)">
                  <i class="bi bi-eye"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div
        class="history-footer d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-2 p-3"
      >
        <div class="text-muted small">
          Página {{ currentPage }} · Mostrando {{ filteredLogs.length }} registros
        </div>
        <div class="d-flex align-items-center gap-2">
          <button
            class="btn btn-outline-dark btn-sm"
            [disabled]="currentPage <= 1 || loading"
            (click)="goToPreviousPage()"
          >
            <i class="bi bi-chevron-left"></i> Anterior
          </button>
          <button
            class="btn btn-outline-dark btn-sm"
            [disabled]="!hasNextPage || loading"
            (click)="goToNextPage()"
          >
            Siguiente <i class="bi bi-chevron-right"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</main>

<!-- Modal Detalle -->
<ng-container *ngIf="showDetailModal && selectedLog">
  <div class="modal d-block" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content cartoon-modal">
        <div class="modal-header border-0 pb-0">
          <h5 class="fw-bold mb-0">Detalle del Registro #{{ selectedLog.id }}</h5>
          <button type="button" class="btn-close" (click)="closeModal()"></button>
        </div>
        <div class="modal-body">
          <div class="row g-4">
            <div class="col-md-6">
              <div class="detail-item p-3 rounded-4">
                <label class="x-small text-muted text-uppercase fw-bold">Actor</label>
                <div class="fw-bold">
                  {{
                    selectedLog.user_name ||
                      (selectedLog.user_id
                        ? 'Usuario ID #' + selectedLog.user_id
                        : 'Proceso del Sistema')
                  }}
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="detail-item p-3 rounded-4">
                <label class="x-small text-muted text-uppercase fw-bold">Fecha Exacta</label>
                <div class="fw-bold">{{ formatDate(selectedLog.timestamp) }}</div>
              </div>
            </div>
            <div class="col-12">
              <div class="detail-item p-3 rounded-4">
                <label class="x-small text-muted text-uppercase fw-bold">Cambios / Datos</label>
                <pre class="changes-pre mt-2">{{ getDetailsJson(selectedLog) }}</pre>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer border-0">
          <button class="btn btn-ink text-white px-4 rounded-pill" (click)="closeModal()">
            Cerrar
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-backdrop fade show"></div>
</ng-container>

// Frontend/src/routes/admin/historial/+page.svelte
<script>
	import { onMount, tick } from 'svelte';
	import Swal from 'sweetalert2';
	import { fly, fade } from 'svelte/transition';
	import AdminNavbar from '$lib/components/AdminNavbar.svelte';
	import { getAuditLogs, exportAuditLogsCSV } from '../../../api/audit_service.js';

	let auditLogs = [];
	let filteredLogs = [];
	let loading = false;
	let showDetailModal = false;
	let selectedLog = null;

	// Filters
	let filterAction = '';
	let filterResource = '';
	let filterUser = '';
	let startDate = '';
	let endDate = '';
	let searchTerm = '';

	// Pagination
	let currentPage = 1;
	let pageSize = 20;
	let pageSizeOptions = [20, 50, 100];

	onMount(async () => {
		await fetchAuditLogs();
	});

	async function fetchAuditLogs() {
		loading = true;
		try {
			const params = {
				limit: pageSize,
				offset: (currentPage - 1) * pageSize
			};

			if (filterAction) params.action = filterAction;
			if (filterResource) params.resource = filterResource;
			if (filterUser) params.user_id = filterUser;
			if (startDate) params.start_date = new Date(startDate).toISOString();
			if (endDate) params.end_date = new Date(endDate).toISOString();

			const response = await getAuditLogs(params);
			auditLogs = Array.isArray(response) ? response : response.data || [];
			applySearch();
		} catch (error) {
			console.error('Error fetching audit logs:', error);
			Swal.fire({
				icon: 'error',
				title: 'Error de Carga',
				text: 'No se pudo obtener el historial. Verifica tu conexión.',
				confirmButtonColor: '#ff6b6b'
			});
		} finally {
			loading = false;
		}
	}

	function applySearch() {
		if (searchTerm.trim() === '') {
			filteredLogs = auditLogs;
		} else {
			const term = searchTerm.toLowerCase();
			filteredLogs = auditLogs.filter(
				(log) =>
					log.action.toLowerCase().includes(term) ||
					log.resource.toLowerCase().includes(term) ||
					(log.details && log.details.toLowerCase().includes(term))
			);
		}
	}

	async function exportToCSV() {
		try {
			const params = {};
			if (filterAction) params.action = filterAction;
			if (filterResource) params.resource = filterResource;
			if (filterUser) params.user_id = filterUser;
			if (startDate) params.start_date = new Date(startDate).toISOString();
			if (endDate) params.end_date = new Date(endDate).toISOString();

			const data = await exportAuditLogsCSV(params);

			const blob = new Blob([data.content], { type: 'text/csv;charset=utf-8;' });
			const url = URL.createObjectURL(blob);
			const element = document.createElement('a');
			element.setAttribute('href', url);
			element.setAttribute('download', data.filename);
			element.style.display = 'none';
			document.body.appendChild(element);
			element.click();
			document.body.removeChild(element);
			URL.revokeObjectURL(url);

			Swal.fire({
				icon: 'success',
				title: '¡Exportado!',
				text: 'El archivo CSV se ha descargado.',
				confirmButtonColor: '#4361ee'
			});
		} catch (error) {
			console.error('Error:', error);
			Swal.fire('Error', 'No se pudo exportar el historial.', 'error');
		}
	}

	async function resetFilters() {
		filterAction = '';
		filterResource = '';
		filterUser = '';
		startDate = '';
		endDate = '';
		searchTerm = '';
		currentPage = 1;
		await fetchAuditLogs();
	}

	function viewDetails(log) {
		selectedLog = log;
		showDetailModal = true;
	}

	function formatDate(dateString) {
		if (!dateString) return '-';
		return new Date(dateString).toLocaleString('es-CO', {
			day: '2-digit',
			month: '2-digit',
			year: 'numeric',
			hour: '2-digit',
			minute: '2-digit'
		});
	}

	function getActionBadge(action) {
		const config = {
			create: { class: 'badge-create', label: 'Crear', icon: 'bi-plus-circle' },
			update: { class: 'badge-update', label: 'Editar', icon: 'bi-pencil' },
			delete: { class: 'badge-delete', label: 'Borrar', icon: 'bi-trash' },
			login: { class: 'badge-login', label: 'Login', icon: 'bi-box-arrow-in-right' },
			login_failed: { class: 'badge-failed', label: 'Fallo', icon: 'bi-exclamation-triangle' }
		};
		return config[action] || { class: 'bg-secondary', label: action, icon: 'bi-dot' };
	}
</script>

<AdminNavbar />

<main class="history-page py-5">
	<div class="container" in:fade>
		<header
			class="d-flex flex-column flex-md-row justify-content-between align-items-end mb-4 gap-3"
		>
			<div in:fly={{ x: -20, duration: 600 }}>
				<span class="history-badge mb-2">📋 Auditoría General</span>
				<h1 class="fw-bold display-6 mb-0">Historial de Actividad</h1>
				<p class="text-muted">Monitorea cada cambio y acción realizada en el sistema.</p>
			</div>

			<div class="d-flex gap-2">
				<button class="btn btn-export shadow-sm" on:click={exportToCSV}>
					<i class="bi bi-download me-2"></i> Exportar CSV
				</button>
			</div>
		</header>

		<!-- Filtros Premium -->
		<div class="card filter-card mb-4 p-4 shadow-sm" in:fly={{ y: 20, duration: 600, delay: 100 }}>
			<div class="row g-3">
				<div class="col-md-3">
					<label class="cartoon-label">Acción</label>
					<select class="form-select cartoon-input" bind:value={filterAction}>
						<option value="">Todas las acciones</option>
						<option value="create">Crear</option>
						<option value="update">Actualizar</option>
						<option value="delete">Eliminar</option>
						<option value="login">Inicio Sesión</option>
					</select>
				</div>
				<div class="col-md-3">
					<label class="cartoon-label">Recurso</label>
					<select class="form-select cartoon-input" bind:value={filterResource}>
						<option value="">Todos los recursos</option>
						<option value="user">Usuarios</option>
						<option value="pet">Mascotas</option>
						<option value="adoption">Adopciones</option>
					</select>
				</div>
				<div class="col-md-4">
					<label class="cartoon-label">Rango de Fechas</label>
					<div class="input-group">
						<input type="date" class="form-control cartoon-input" bind:value={startDate} />
						<span class="input-group-text bg-transparent border-0">al</span>
						<input type="date" class="form-control cartoon-input" bind:value={endDate} />
					</div>
				</div>
				<div class="col-md-2 d-flex align-items-end gap-2">
					<button class="btn btn-search w-100" on:click={fetchAuditLogs}>
						<i class="bi bi-search"></i>
					</button>
					<button class="btn btn-outline-secondary rounded-pill" on:click={resetFilters}>
						<i class="bi bi-arrow-counterclockwise"></i>
					</button>
				</div>
			</div>
		</div>

		<!-- Búsqueda rápida -->
		<div class="search-box mb-4" in:fly={{ y: 20, duration: 600, delay: 200 }}>
			<input
				type="text"
				class="form-control form-control-lg cartoon-input ps-4"
				placeholder="🔍 Buscar por detalles, recurso o usuario..."
				bind:value={searchTerm}
				on:input={applySearch}
			/>
		</div>

		<!-- Tabla Premium -->
		<div
			class="card border-0 shadow-sm rounded-4 overflow-hidden"
			in:fly={{ y: 20, duration: 600, delay: 300 }}
		>
			<div class="table-responsive">
				<table class="table table-hover align-middle mb-0">
					<thead class="table-ink text-white">
						<tr>
							<th class="ps-4">Usuario</th>
							<th>Acción</th>
							<th>Recurso</th>
							<th>Fecha y Hora</th>
							<th>Estado</th>
							<th class="text-center pe-4">Detalle</th>
						</tr>
					</thead>
					<tbody>
						{#if loading}
							<tr>
								<td colspan="6" class="text-center py-5">
									<div class="spinner-border text-mustard" role="status"></div>
									<p class="mt-2 fw-bold">Cargando bitácora...</p>
								</td>
							</tr>
						{:else if filteredLogs.length === 0}
							<tr>
								<td colspan="6" class="text-center py-5 text-muted">
									<i class="bi bi-journal-x display-4 d-block mb-3 opacity-20"></i>
									No se encontraron registros con esos filtros.
								</td>
							</tr>
						{:else}
							{#each filteredLogs as log (log.id)}
								<tr class="log-row">
									<td class="ps-4">
										<div class="d-flex align-items-center gap-2">
											<div class="user-avatar-small">
												{log.user_id ? 'U' : 'S'}
											</div>
											<div>
												<div class="fw-bold small">
													{log.user_id ? `Usuario #${log.user_id}` : 'Sistema'}
												</div>
												<div class="text-muted x-small">{log.ip_address || 'Sin IP'}</div>
											</div>
										</div>
									</td>
									<td>
										<span class="badge-cartoon {getActionBadge(log.action).class}">
											<i class="bi {getActionBadge(log.action).icon} me-1"></i>
											{getActionBadge(log.action).label}
										</span>
									</td>
									<td>
										<span class="fw-bold text-dark">{log.resource}</span>
										<span class="text-muted small">#{log.resource_id || '-'}</span>
									</td>
									<td class="text-muted small">{formatDate(log.timestamp)}</td>
									<td>
										{#if log.status === 'success'}
											<span class="text-success small fw-bold"
												><i class="bi bi-check-circle-fill"></i> Ok</span
											>
										{:else}
											<span class="text-danger small fw-bold"
												><i class="bi bi-x-circle-fill"></i> Error</span
											>
										{/if}
									</td>
									<td class="text-center pe-4">
										<button class="btn btn-detail-circle" on:click={() => viewDetails(log)}>
											<i class="bi bi-eye"></i>
										</button>
									</td>
								</tr>
							{/each}
						{/if}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>

<!-- Modal Detalle Cartoon -->
{#if showDetailModal && selectedLog}
	<div class="modal d-block" tabindex="-1" in:fade>
		<div class="modal-dialog modal-dialog-centered modal-lg">
			<div class="modal-content cartoon-modal">
				<div class="modal-header border-0 pb-0">
					<h5 class="fw-bold mb-0">Detalle del Registro #{selectedLog.id}</h5>
					<button type="button" class="btn-close" on:click={() => (showDetailModal = false)}
					></button>
				</div>
				<div class="modal-body">
					<div class="row g-4">
						<div class="col-md-6">
							<div class="detail-item p-3 rounded-4">
								<label class="x-small text-muted text-uppercase fw-bold">Actor</label>
								<div class="fw-bold">
									{selectedLog.user_id
										? `Usuario ID #${selectedLog.user_id}`
										: 'Proceso del Sistema'}
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="detail-item p-3 rounded-4">
								<label class="x-small text-muted text-uppercase fw-bold">Fecha Exacta</label>
								<div class="fw-bold">{formatDate(selectedLog.timestamp)}</div>
							</div>
						</div>
						<div class="col-12">
							<div class="detail-item p-3 rounded-4">
								<label class="x-small text-muted text-uppercase fw-bold">Cambios / Datos</label>
								<pre class="changes-pre mt-2">{JSON.stringify(
										selectedLog.changes || selectedLog.details,
										null,
										2
									)}</pre>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer border-0">
					<button
						type="button"
						class="btn btn-ink text-white px-4 rounded-pill"
						on:click={() => (showDetailModal = false)}>Cerrar</button
					>
				</div>
			</div>
		</div>
	</div>
	<div class="modal-backdrop fade show"></div>
{/if}

<style>
	.history-page {
		background: var(--cream);
		min-height: 100vh;
		font-family: var(--font-body);
	}

	.history-badge {
		background: var(--mustard);
		color: var(--ink);
		font-weight: 800;
		padding: 4px 16px;
		border-radius: 50px;
		display: inline-block;
		border: 2px solid var(--ink);
		font-size: 0.85rem;
	}

	.filter-card {
		border: 3px solid var(--ink);
		border-radius: 20px;
		box-shadow: 6px 6px 0 var(--ink);
	}

	.cartoon-label {
		font-family: var(--font-display);
		font-weight: 700;
		font-size: 0.9rem;
		color: var(--ink);
		margin-bottom: 5px;
	}

	.cartoon-input {
		border: 2.5px solid var(--ink) !important;
		border-radius: 12px !important;
		font-weight: 600;
		font-size: 0.9rem;
	}

	.btn-search {
		background: var(--coral);
		color: white;
		border: 2.5px solid var(--ink);
		border-radius: 12px;
		height: 45px;
		box-shadow: 3px 3px 0 var(--ink);
		transition: all 0.2s;
	}

	.btn-search:hover {
		transform: translate(-2px, -2px);
		box-shadow: 5px 5px 0 var(--ink);
	}

	.btn-export {
		background: white;
		border: 2.5px solid var(--ink);
		border-radius: 50px;
		font-weight: 700;
		padding: 8px 20px;
		box-shadow: 4px 4px 0 var(--ink);
		transition: all 0.2s;
	}

	.btn-export:hover {
		background: var(--mustard);
		transform: translateY(-2px);
	}

	.table-ink {
		background: var(--ink);
	}

	.table-ink th {
		font-family: var(--font-display);
		font-weight: 700;
		font-size: 0.8rem;
		letter-spacing: 1px;
		border: none;
		padding: 15px;
	}

	.log-row:hover {
		background-color: rgba(245, 183, 49, 0.05);
	}

	.user-avatar-small {
		width: 32px;
		height: 32px;
		background: var(--mustard);
		border: 2px solid var(--ink);
		border-radius: 8px;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 900;
		font-size: 0.8rem;
	}

	.badge-cartoon {
		padding: 4px 12px;
		border-radius: 8px;
		font-size: 0.75rem;
		font-weight: 800;
		border: 2px solid var(--ink);
		display: inline-flex;
		align-items: center;
	}

	.badge-create {
		background: #c8e6c9;
		color: #2e7d32;
	}
	.badge-update {
		background: #bbdefb;
		color: #1565c0;
	}
	.badge-delete {
		background: #ffcdd2;
		color: #c62828;
	}
	.badge-login {
		background: #e1bee7;
		color: #6a1b9a;
	}
	.badge-failed {
		background: #fff9c4;
		color: #f9a825;
	}

	.btn-detail-circle {
		width: 35px;
		height: 35px;
		border-radius: 50%;
		border: 2px solid var(--ink);
		background: white;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		transition: all 0.2s;
	}

	.btn-detail-circle:hover {
		background: var(--mustard);
		transform: scale(1.1);
	}

	.cartoon-modal {
		border: 4px solid var(--ink);
		border-radius: 30px;
		box-shadow: 10px 10px 0 var(--ink);
	}

	.detail-item {
		background: #f8f9fa;
		border: 2px solid #eee;
	}

	.changes-pre {
		background: #222;
		color: #00ff00;
		padding: 15px;
		border-radius: 10px;
		max-height: 300px;
		overflow-y: auto;
		font-size: 0.8rem;
	}

	.btn-ink {
		background: var(--ink);
		color: white;
	}

	.x-small {
		font-size: 0.7rem;
	}
	.opacity-20 {
		opacity: 0.2;
	}
</style>
